/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PasienController;
import model.Pasien;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Enhadeee
 */
public class ResepsionisFrame extends javax.swing.JFrame {
    private User currentUser;
    private final PasienController controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResepsionisFrame.class.getName());
    
    /**
     * Creates new form ResepsionisFrame
     */
    public ResepsionisFrame() {
        initComponents();
        controller = new PasienController();
        setLocationRelativeTo(null);
        // Mode testing - tidak ada user yang login
        setupUI(null);
    }
    
    public ResepsionisFrame(User user) {
        this.currentUser = user;
        initComponents();
        controller = new PasienController();
        setLocationRelativeTo(null);
        setupUI(user);
    }
    
    private void setupUI(User user) {
        if (user != null) {
            // Update judul window
            setTitle("Dashboard " + user.getRole() + " - Input Pasien");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jRadioButtonPerempuan = new javax.swing.JRadioButton();
        jLabelJk = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jComboBoxPenanganan = new javax.swing.JComboBox<>();
        jTextFieldId = new javax.swing.JTextField();
        jLabelPenanganan = new javax.swing.JLabel();
        jRadioButtonLaki = new javax.swing.JRadioButton();
        jButtonClear = new javax.swing.JButton();
        jLabelDataPasien = new javax.swing.JLabel();
        jLabelCatatan = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaCatatan = new javax.swing.JTextArea();
        jButtonTambah = new javax.swing.JButton();
        jButtonLogOut1 = new javax.swing.JButton();
        jButtonLihatData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNama.setText("Nama");

        jTextFieldNama.addActionListener(this::jTextFieldNamaActionPerformed);

        buttonGroup1.add(jRadioButtonPerempuan);
        jRadioButtonPerempuan.setText("Perempuan");

        jLabelJk.setText("Jenis Kelamin");

        jLabelId.setText("No Identitas");

        jComboBoxPenanganan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rawat Inap", "Rawat Jalan" }));

        jLabelPenanganan.setText("Penanganan");

        buttonGroup1.add(jRadioButtonLaki);
        jRadioButtonLaki.setText("Laki-Laki");
        jRadioButtonLaki.addActionListener(this::jRadioButtonLakiActionPerformed);

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(this::jButtonClearActionPerformed);

        jLabelDataPasien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelDataPasien.setText("Masukkan Data Pasien");

        jLabelCatatan.setText("Catatan");

        jTextAreaCatatan.setColumns(20);
        jTextAreaCatatan.setRows(5);
        jScrollPane4.setViewportView(jTextAreaCatatan);

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(this::jButtonTambahActionPerformed);

        jButtonLogOut1.setText("Log Out");
        jButtonLogOut1.addActionListener(this::jButtonLogOut1ActionPerformed);

        jButtonLihatData.setText("Lihat Data");
        jButtonLihatData.addActionListener(this::jButtonLihatDataActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDataPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLihatData)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogOut1))
                    .addComponent(jLabelJk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNama)
                    .addComponent(jTextFieldId)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxPenanganan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelCatatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPenanganan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(398, 398, 398))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jButtonLogOut1)
                    .addComponent(jButtonLihatData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelJk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLaki)
                    .addComponent(jRadioButtonPerempuan))
                .addGap(9, 9, 9)
                .addComponent(jLabelPenanganan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPenanganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCatatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonClear))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
        jButtonTambah.requestFocus();
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jRadioButtonLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLakiActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        // 1. Load Data dari View
        String noId = jTextFieldId.getText().trim();
        String nama = jTextFieldNama.getText().trim();
        String jk = jRadioButtonLaki.isSelected() ? "Laki-Laki" : "Perempuan";
        String penanganan = (String) jComboBoxPenanganan.getSelectedItem();
        String catatan = jTextAreaCatatan.getText().trim();

        Pasien pasien = new Pasien(noId, nama, jk, penanganan, catatan) {};

        // 2. Delegasi ke Controller
        boolean sukses = controller.handleTambah(pasien);

        // 3. View merespons hasil Controller
        if (sukses) {
            JOptionPane.showMessageDialog(this, "Data pasien berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            handleClear();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan! Pastikan ID unik dan Nama tidak kosong.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        handleClear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOut1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new MenuFrame().setVisible(true);
    }//GEN-LAST:event_jButtonLogOut1ActionPerformed

    private void jButtonLihatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatDataActionPerformed
        // TODO add your handling code here:
        dispose();
        new AdminFrame(currentUser).setVisible(true);
    }//GEN-LAST:event_jButtonLihatDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ResepsionisFrame().setVisible(true));
    }
        // Helper View-only
    private void handleClear() {
        jTextFieldId.setText("");
        jTextFieldNama.setText("");
        buttonGroup1.clearSelection();
        jComboBoxPenanganan.setSelectedIndex(0);
        jTextAreaCatatan.setText("");
        jTextFieldId.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonLihatData;
    private javax.swing.JButton jButtonLogOut1;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JComboBox<String> jComboBoxPenanganan;
    private javax.swing.JLabel jLabelCatatan;
    private javax.swing.JLabel jLabelDataPasien;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelJk;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelPenanganan;
    private javax.swing.JRadioButton jRadioButtonLaki;
    private javax.swing.JRadioButton jRadioButtonPerempuan;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaCatatan;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
